### ISSUE TITLE
How to make HardwareEvent with pgina?

### ISSUE THREAD

**Issue by gotoco** [pgina/pgina#243]
Hello, I trying to create logon process based on external device that is connected by serialPort to Windows and it can logon user based on hardware key (in example RFID card).
At microsoft side there are Windows Credential HardwareEvent demo, and I need to write some process that after lockscreen will be waiting for command from serialPort and when it occurs my plugin will unlock screen and logon user.

My question is how to achieve that functionality with pGina?
I develop some functionality based on demoplugin that authenticate user by SerialPort (I added flag based on messages from serialPort to Authentication checkin) but it still need user to press Enter to logon.
Can this process will be automatically?

**Comment by daw42** [comment]
Plugins currently can't do this, but you could modify the credential provider code to monitor the serial port.  You might also want to use auto logon so that the user doesn't need to press the "enter" key or click the arrow.  Here's a related discussion on SO:  
http://stackoverflow.com/questions/8619323/windows7-credential-provider-to-automatically-logon-user-on-the-hardware-event

**Comment by nate-yocom** [comment]
This starts to reach the border of what pGina is intended to help with.  Please do feel free to use it as a credprov sample, but I do not think pGina with hardware tokens via plugin support is on the roadmap right now....
